### PR TITLE
[Integration][AWS] - RFC3339 format for organization account timestamps

### PR DESCRIPTION
**Pull request by shariff-6**
# Description

What - Bug | Date-Time Format Discrepancies in Ports AWS Integration

Why -DateTime format from AWS for Account Organisation is not RFC 3339 compatible

How - 
Replace space delimiter with 'T' in JoinedTimestamp mapping to comply with RFC3339 timestamp format specification

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

<h4> All tests should be run against the port production environment(using a testing org). </h4>

### Core testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync finishes successfully
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Scheduled resync able to abort existing resync and start a new one
- [ ] Tested with at least 2 integrations from scratch
- [ ] Tested with Kafka and Polling event listeners
- [ ] Tested deletion of entities that don't pass the selector

### Integration testing checklist

- [ ] Integration able to create all default resources from scratch
- [ ] Resync able to create entities
- [ ] Resync able to update entities
- [ ] Resync able to detect and delete entities
- [ ] Resync finishes successfully
- [ ] If new resource kind is added or updated in the integration, add example raw data, mapping and expected result to the `examples` folder in the integration directory.
- [ ] If resource kind is updated, run the integration with the example data and check if the expected result is achieved
- [ ] If new resource kind is added or updated, validate that live-events for that resource are working as expected
- [ ] Docs PR link [here](#)

### Preflight checklist

- [ ] Handled rate limiting
- [ ] Handled pagination
- [ ] Implemented the code in async
- [ ] Support Multi account

## Screenshots
Previous State
Screenshot 2024-10-25 at 1 59 29 PM (1)

Fix
Fix

### CODE REVIEW

**Review by PeyGis — APPROVED** [review]
LGTM

**Review by PeyGis — CHANGES_REQUESTED** [review]
we need to bump the integration version, and write a changelog for it

**Review by Tankilevitch — COMMENTED** [review]
missing update of pyproject.toml

**Review by Tankilevitch — APPROVED** [review]
LGTM

**Review by PeyGis — APPROVED** [review]
lgtm

**Pull request merged**
